package com.ensa.gestiongarderie.enums;

public enum TypeEnfant {
    ENFANT_NORMAL,
    ENFANT_AUTISTE,
    ENFANT_HYPERACTIF,
    ENFANT_SURDOUE,
    ENFANT_AUTISTE_ET_HYPERACTIF,
    ENFANT_AUTISTE_ET_SURDOUE,
    ENFANT_SURDOUE_ET_HYPERACTIF,
    ENFANT_AUTIST_ET_HYPERACTIF_ET_SURDOUE
}
